services:
  - type: web
    name: jravis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash -c "export PYTHONPATH=. && uvicorn main:app --host 0.0.0.0 --port $PORT"

  - type: worker
    name: jravis-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
